### ISSUE TITLE
Feature Request: Per-Project Header Blocks

### ISSUE THREAD

**Issue by adamcaudill** [hkgnp/logseq-todoist-plugin-ts#5]
I use my Daily Notes for both work and personal tasks, ideally it would be nice to be able to specify a different header block value on a Todoist project basis. 

So, what I'd like to do is specify `[[Personal Task Inbox]]` for one Todoist project, and `[[Work Task Inbox]]` for another project. This way I can keep them separate, and not mix work and personal tasks.

**Comment by hkgnp** [comment]
Feature added.
